spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: 20021210hjh
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
